version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
  - package-ecosystem: "npm"
    directory: "/admin-panel"
    schedule:
      interval: "weekly"
