<<<<<<< HEAD
[versions]
kotlin = "1.9.24"
ktor = "2.3.12"
telegram = "6.1.0"
coroutines = "1.8.1"
exposed = "0.50.0"
flyway = "10.15.0"
postgres = "42.7.7"
hikaricp = "6.3.0"
config = "1.4.3"
dotenv = "6.3.1"
logback = "1.5.18"
koin = "3.5.6"
jwt = "4.4.0"
h2 = "2.1.214"
junit = "5.10.2"
mockito = "5.18.0"
mockitoKotlin = "5.4.0"
wiremock = "3.0.1"
lettuce = "6.7.1.RELEASE"
caffeine = "3.2.0"
serializationJson = "1.9.0"
jedis = "6.0.0"
embeddedRedis = "0.7.3"
backoff = "0.4.0"

[libraries]
exposed-bom = { module = "org.jetbrains.exposed:exposed-bom", version.ref = "exposed" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time" }

flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
typesafe-config = { module = "com.typesafe:config", version.ref = "config" }
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }

kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
wiremock = { module = "com.github.tomakehurst:wiremock-jre8", version.ref = "wiremock" }

h2 = { module = "com.h2database:h2", version.ref = "h2" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "jwt" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
telegram-bot = { module = "io.github.kotlintelegrambot:telegram", version.ref = "telegram" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }

ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-content-negotiation-jvm = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json-jvm = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-server-auth-jvm = { module = "io.ktor:ktor-server-auth-jvm", version.ref = "ktor" }
ktor-server-auth-jwt-jvm = { module = "io.ktor:ktor-server-auth-jwt-jvm", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-test-host-jvm = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
embedded-redis = { module = "it.ozimov:embedded-redis", version.ref = "embeddedRedis" }
ktor-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-metrics = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
backoff = { module = "io.github.reugn:kotlin-backoff", version.ref = "backoff" }
=======
# This file was generated by the Gradle 'init' task.
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# Обновляем версию Kotlin для совместимости API
kotlin = "1.9.24"
ktor = "2.3.0"
logback = "1.4.7"
exposed = "0.41.1"
postgresql = "42.6.0"
h2 = "2.1.214"
hikariCP = "5.0.1"
flyway = "9.19.1"
koin = "3.4.0"
telegram = "6.9.0"
kotlin-logging = "3.0.5"
micrometer = "1.11.0"
jedis = "4.4.3"
zxing = "3.5.1"
auth0-jwt = "4.4.0"
backoff = "0.4.0"
detekt = "1.23.0"

# Test dependencies
junit = "5.9.2"
mockk = "1.13.5"
strikt = "0.34.1"
testcontainers = "1.18.1"

[libraries]
# Core
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
hikariCP = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCP" }
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }
telegram-bot = { module = "org.telegram:telegrambots", version.ref = "telegram" }
kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version.ref = "micrometer" }
ktor-server-metrics-micrometer = { group = "io.ktor", name = "ktor-server-metrics-micrometer-jvm", version.ref = "ktor" }
jedis = { group = "redis.clients", name = "jedis", version.ref = "jedis" }
google-zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
google-zxing-javase = { group = "com.google.zxing", name = "javase", version.ref = "zxing" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-call-logging = { group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json-client = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
backoff = { module = "io.github.reugn:kotlin-backoff", version.ref = "backoff" }

# Test dependencies
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
ktor-server-tests = { group = "io.ktor", name = "ktor-server-tests-jvm", version.ref = "ktor" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
strikt-core = { group = "io.strikt", name = "strikt-core", version.ref = "strikt" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
>>>>>>> 884cda7 (add ch)
