name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - name: Run dependency-check & upload SBOM
        run: ./gradlew dependencyCheckAnalyze
      - name: Start monitoring stack
        run: docker compose -f docker-compose.monitoring.yml up -d
